//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZHotKey.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EZHotKey.Core.Resources.KeyNames", typeof(KeyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Mouse Button.
        /// </summary>
        internal static string _0x01 {
            get {
                return ResourceManager.GetString("0x01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Mouse Button.
        /// </summary>
        internal static string _0x02 {
            get {
                return ResourceManager.GetString("0x02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control-break processing.
        /// </summary>
        internal static string _0x03 {
            get {
                return ResourceManager.GetString("0x03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Mouse Button.
        /// </summary>
        internal static string _0x04 {
            get {
                return ResourceManager.GetString("0x04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Back Button.
        /// </summary>
        internal static string _0x05 {
            get {
                return ResourceManager.GetString("0x05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Forward Button.
        /// </summary>
        internal static string _0x06 {
            get {
                return ResourceManager.GetString("0x06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backspace.
        /// </summary>
        internal static string _0x08 {
            get {
                return ResourceManager.GetString("0x08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAB.
        /// </summary>
        internal static string _0x09 {
            get {
                return ResourceManager.GetString("0x09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR Key ⌧.
        /// </summary>
        internal static string _0x0C {
            get {
                return ResourceManager.GetString("0x0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string _0x0D {
            get {
                return ResourceManager.GetString("0x0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Shift Key.
        /// </summary>
        internal static string _0x10 {
            get {
                return ResourceManager.GetString("0x10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Control Key.
        /// </summary>
        internal static string _0x11 {
            get {
                return ResourceManager.GetString("0x11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Alt Key.
        /// </summary>
        internal static string _0x12 {
            get {
                return ResourceManager.GetString("0x12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Key.
        /// </summary>
        internal static string _0x13 {
            get {
                return ResourceManager.GetString("0x13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock.
        /// </summary>
        internal static string _0x14 {
            get {
                return ResourceManager.GetString("0x14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC Key.
        /// </summary>
        internal static string _0x1B {
            get {
                return ResourceManager.GetString("0x1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacebar.
        /// </summary>
        internal static string _0x20 {
            get {
                return ResourceManager.GetString("0x20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageUp.
        /// </summary>
        internal static string _0x21 {
            get {
                return ResourceManager.GetString("0x21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageDown.
        /// </summary>
        internal static string _0x22 {
            get {
                return ResourceManager.GetString("0x22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END Key.
        /// </summary>
        internal static string _0x23 {
            get {
                return ResourceManager.GetString("0x23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME Key.
        /// </summary>
        internal static string _0x24 {
            get {
                return ResourceManager.GetString("0x24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Arrow Key.
        /// </summary>
        internal static string _0x25 {
            get {
                return ResourceManager.GetString("0x25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Arrow Key.
        /// </summary>
        internal static string _0x26 {
            get {
                return ResourceManager.GetString("0x26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Arrow Key.
        /// </summary>
        internal static string _0x27 {
            get {
                return ResourceManager.GetString("0x27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Arrow Key.
        /// </summary>
        internal static string _0x28 {
            get {
                return ResourceManager.GetString("0x28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Key.
        /// </summary>
        internal static string _0x29 {
            get {
                return ResourceManager.GetString("0x29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT Key.
        /// </summary>
        internal static string _0x2A {
            get {
                return ResourceManager.GetString("0x2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE Key.
        /// </summary>
        internal static string _0x2B {
            get {
                return ResourceManager.GetString("0x2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT SCREEN Key.
        /// </summary>
        internal static string _0x2C {
            get {
                return ResourceManager.GetString("0x2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT Key.
        /// </summary>
        internal static string _0x2D {
            get {
                return ResourceManager.GetString("0x2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE Key.
        /// </summary>
        internal static string _0x2E {
            get {
                return ResourceManager.GetString("0x2E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP Key.
        /// </summary>
        internal static string _0x2F {
            get {
                return ResourceManager.GetString("0x2F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 0 Key.
        /// </summary>
        internal static string _0x30 {
            get {
                return ResourceManager.GetString("0x30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 1 Key.
        /// </summary>
        internal static string _0x31 {
            get {
                return ResourceManager.GetString("0x31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 2 Key.
        /// </summary>
        internal static string _0x32 {
            get {
                return ResourceManager.GetString("0x32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 3 Key.
        /// </summary>
        internal static string _0x33 {
            get {
                return ResourceManager.GetString("0x33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 4 Key.
        /// </summary>
        internal static string _0x34 {
            get {
                return ResourceManager.GetString("0x34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 5 Key.
        /// </summary>
        internal static string _0x35 {
            get {
                return ResourceManager.GetString("0x35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 6 Key.
        /// </summary>
        internal static string _0x36 {
            get {
                return ResourceManager.GetString("0x36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 7 Key.
        /// </summary>
        internal static string _0x37 {
            get {
                return ResourceManager.GetString("0x37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 8 Key.
        /// </summary>
        internal static string _0x38 {
            get {
                return ResourceManager.GetString("0x38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 9 Key.
        /// </summary>
        internal static string _0x39 {
            get {
                return ResourceManager.GetString("0x39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Key.
        /// </summary>
        internal static string _0x41 {
            get {
                return ResourceManager.GetString("0x41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Key.
        /// </summary>
        internal static string _0x42 {
            get {
                return ResourceManager.GetString("0x42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Key.
        /// </summary>
        internal static string _0x43 {
            get {
                return ResourceManager.GetString("0x43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D Key.
        /// </summary>
        internal static string _0x44 {
            get {
                return ResourceManager.GetString("0x44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Key.
        /// </summary>
        internal static string _0x45 {
            get {
                return ResourceManager.GetString("0x45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F Key.
        /// </summary>
        internal static string _0x46 {
            get {
                return ResourceManager.GetString("0x46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G Key.
        /// </summary>
        internal static string _0x47 {
            get {
                return ResourceManager.GetString("0x47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H Key.
        /// </summary>
        internal static string _0x48 {
            get {
                return ResourceManager.GetString("0x48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Key.
        /// </summary>
        internal static string _0x49 {
            get {
                return ResourceManager.GetString("0x49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J Key.
        /// </summary>
        internal static string _0x4A {
            get {
                return ResourceManager.GetString("0x4A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K Key.
        /// </summary>
        internal static string _0x4B {
            get {
                return ResourceManager.GetString("0x4B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L Key.
        /// </summary>
        internal static string _0x4C {
            get {
                return ResourceManager.GetString("0x4C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M Key.
        /// </summary>
        internal static string _0x4D {
            get {
                return ResourceManager.GetString("0x4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N Key.
        /// </summary>
        internal static string _0x4E {
            get {
                return ResourceManager.GetString("0x4E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Key.
        /// </summary>
        internal static string _0x4F {
            get {
                return ResourceManager.GetString("0x4F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P Key.
        /// </summary>
        internal static string _0x50 {
            get {
                return ResourceManager.GetString("0x50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q Key.
        /// </summary>
        internal static string _0x51 {
            get {
                return ResourceManager.GetString("0x51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Key.
        /// </summary>
        internal static string _0x52 {
            get {
                return ResourceManager.GetString("0x52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S Key.
        /// </summary>
        internal static string _0x53 {
            get {
                return ResourceManager.GetString("0x53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Key.
        /// </summary>
        internal static string _0x54 {
            get {
                return ResourceManager.GetString("0x54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U Key.
        /// </summary>
        internal static string _0x55 {
            get {
                return ResourceManager.GetString("0x55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V Key.
        /// </summary>
        internal static string _0x56 {
            get {
                return ResourceManager.GetString("0x56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W Key.
        /// </summary>
        internal static string _0x57 {
            get {
                return ResourceManager.GetString("0x57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Key.
        /// </summary>
        internal static string _0x58 {
            get {
                return ResourceManager.GetString("0x58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Key.
        /// </summary>
        internal static string _0x59 {
            get {
                return ResourceManager.GetString("0x59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Key.
        /// </summary>
        internal static string _0x5A {
            get {
                return ResourceManager.GetString("0x5A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Windows Key.
        /// </summary>
        internal static string _0x5B {
            get {
                return ResourceManager.GetString("0x5B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Windows Key.
        /// </summary>
        internal static string _0x5C {
            get {
                return ResourceManager.GetString("0x5C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps Key.
        /// </summary>
        internal static string _0x5D {
            get {
                return ResourceManager.GetString("0x5D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Key.
        /// </summary>
        internal static string _0x5F {
            get {
                return ResourceManager.GetString("0x5F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumPad 0.
        /// </summary>
        internal static string _0x60 {
            get {
                return ResourceManager.GetString("0x60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumPad 1.
        /// </summary>
        internal static string _0x61 {
            get {
                return ResourceManager.GetString("0x61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumPad 2.
        /// </summary>
        internal static string _0x62 {
            get {
                return ResourceManager.GetString("0x62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumPad 3.
        /// </summary>
        internal static string _0x63 {
            get {
                return ResourceManager.GetString("0x63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumPad 4.
        /// </summary>
        internal static string _0x64 {
            get {
                return ResourceManager.GetString("0x64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumPad 5.
        /// </summary>
        internal static string _0x65 {
            get {
                return ResourceManager.GetString("0x65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumPad 6.
        /// </summary>
        internal static string _0x66 {
            get {
                return ResourceManager.GetString("0x66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumPad 7.
        /// </summary>
        internal static string _0x67 {
            get {
                return ResourceManager.GetString("0x67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumPad 8.
        /// </summary>
        internal static string _0x68 {
            get {
                return ResourceManager.GetString("0x68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumPad 9.
        /// </summary>
        internal static string _0x69 {
            get {
                return ResourceManager.GetString("0x69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply Key.
        /// </summary>
        internal static string _0x6A {
            get {
                return ResourceManager.GetString("0x6A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Key.
        /// </summary>
        internal static string _0x6B {
            get {
                return ResourceManager.GetString("0x6B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator Key.
        /// </summary>
        internal static string _0x6C {
            get {
                return ResourceManager.GetString("0x6C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract Key.
        /// </summary>
        internal static string _0x6D {
            get {
                return ResourceManager.GetString("0x6D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Key.
        /// </summary>
        internal static string _0x6E {
            get {
                return ResourceManager.GetString("0x6E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide Key.
        /// </summary>
        internal static string _0x6F {
            get {
                return ResourceManager.GetString("0x6F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 Key.
        /// </summary>
        internal static string _0x70 {
            get {
                return ResourceManager.GetString("0x70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2 Key.
        /// </summary>
        internal static string _0x71 {
            get {
                return ResourceManager.GetString("0x71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3 Key.
        /// </summary>
        internal static string _0x72 {
            get {
                return ResourceManager.GetString("0x72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4 Key.
        /// </summary>
        internal static string _0x73 {
            get {
                return ResourceManager.GetString("0x73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5 Key.
        /// </summary>
        internal static string _0x74 {
            get {
                return ResourceManager.GetString("0x74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F6 Key.
        /// </summary>
        internal static string _0x75 {
            get {
                return ResourceManager.GetString("0x75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F7 Key.
        /// </summary>
        internal static string _0x76 {
            get {
                return ResourceManager.GetString("0x76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F8 Key.
        /// </summary>
        internal static string _0x77 {
            get {
                return ResourceManager.GetString("0x77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F9 Key.
        /// </summary>
        internal static string _0x78 {
            get {
                return ResourceManager.GetString("0x78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F10 Key.
        /// </summary>
        internal static string _0x79 {
            get {
                return ResourceManager.GetString("0x79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F11 Key.
        /// </summary>
        internal static string _0x7A {
            get {
                return ResourceManager.GetString("0x7A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F12 Key.
        /// </summary>
        internal static string _0x7B {
            get {
                return ResourceManager.GetString("0x7B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F13 Key.
        /// </summary>
        internal static string _0x7C {
            get {
                return ResourceManager.GetString("0x7C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F14 Key.
        /// </summary>
        internal static string _0x7D {
            get {
                return ResourceManager.GetString("0x7D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F15 Key.
        /// </summary>
        internal static string _0x7E {
            get {
                return ResourceManager.GetString("0x7E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F16 Key.
        /// </summary>
        internal static string _0x7F {
            get {
                return ResourceManager.GetString("0x7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F17 Key.
        /// </summary>
        internal static string _0x80 {
            get {
                return ResourceManager.GetString("0x80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F18 Key.
        /// </summary>
        internal static string _0x81 {
            get {
                return ResourceManager.GetString("0x81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F19 Key.
        /// </summary>
        internal static string _0x82 {
            get {
                return ResourceManager.GetString("0x82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F20 Key.
        /// </summary>
        internal static string _0x83 {
            get {
                return ResourceManager.GetString("0x83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F21 Key.
        /// </summary>
        internal static string _0x84 {
            get {
                return ResourceManager.GetString("0x84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F22 Key.
        /// </summary>
        internal static string _0x85 {
            get {
                return ResourceManager.GetString("0x85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F23 Key.
        /// </summary>
        internal static string _0x86 {
            get {
                return ResourceManager.GetString("0x86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F24 Key.
        /// </summary>
        internal static string _0x87 {
            get {
                return ResourceManager.GetString("0x87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left SHIFT Key.
        /// </summary>
        internal static string _0xA0 {
            get {
                return ResourceManager.GetString("0xA0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right SHIFT Key.
        /// </summary>
        internal static string _0xA1 {
            get {
                return ResourceManager.GetString("0xA1", resourceCulture);
            }
        }
    }
}
