//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZHotKey.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KeyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyNames() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EZHotKey.Core.Resources.KeyNames", typeof(KeyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Mouse Button.
        /// </summary>
        public static string _0x01 {
            get {
                return ResourceManager.GetString("0x01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Mouse Button.
        /// </summary>
        public static string _0x02 {
            get {
                return ResourceManager.GetString("0x02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control-break processing.
        /// </summary>
        public static string _0x03 {
            get {
                return ResourceManager.GetString("0x03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Center Mouse Button.
        /// </summary>
        public static string _0x04 {
            get {
                return ResourceManager.GetString("0x04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Back Button.
        /// </summary>
        public static string _0x05 {
            get {
                return ResourceManager.GetString("0x05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Forward Button.
        /// </summary>
        public static string _0x06 {
            get {
                return ResourceManager.GetString("0x06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Backspace.
        /// </summary>
        public static string _0x08 {
            get {
                return ResourceManager.GetString("0x08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TAB.
        /// </summary>
        public static string _0x09 {
            get {
                return ResourceManager.GetString("0x09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLEAR Key ⌧.
        /// </summary>
        public static string _0x0C {
            get {
                return ResourceManager.GetString("0x0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter.
        /// </summary>
        public static string _0x0D {
            get {
                return ResourceManager.GetString("0x0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Any Shift Key.
        /// </summary>
        public static string _0x10 {
            get {
                return ResourceManager.GetString("0x10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Any Control Key.
        /// </summary>
        public static string _0x11 {
            get {
                return ResourceManager.GetString("0x11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Any Alt Key.
        /// </summary>
        public static string _0x12 {
            get {
                return ResourceManager.GetString("0x12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pause Key.
        /// </summary>
        public static string _0x13 {
            get {
                return ResourceManager.GetString("0x13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caps Lock.
        /// </summary>
        public static string _0x14 {
            get {
                return ResourceManager.GetString("0x14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESC Key.
        /// </summary>
        public static string _0x1B {
            get {
                return ResourceManager.GetString("0x1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spacebar.
        /// </summary>
        public static string _0x20 {
            get {
                return ResourceManager.GetString("0x20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PageUp.
        /// </summary>
        public static string _0x21 {
            get {
                return ResourceManager.GetString("0x21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PageDown.
        /// </summary>
        public static string _0x22 {
            get {
                return ResourceManager.GetString("0x22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a END Key.
        /// </summary>
        public static string _0x23 {
            get {
                return ResourceManager.GetString("0x23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HOME Key.
        /// </summary>
        public static string _0x24 {
            get {
                return ResourceManager.GetString("0x24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Arrow Key.
        /// </summary>
        public static string _0x25 {
            get {
                return ResourceManager.GetString("0x25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Up Arrow Key.
        /// </summary>
        public static string _0x26 {
            get {
                return ResourceManager.GetString("0x26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Arrow Key.
        /// </summary>
        public static string _0x27 {
            get {
                return ResourceManager.GetString("0x27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Down Arrow Key.
        /// </summary>
        public static string _0x28 {
            get {
                return ResourceManager.GetString("0x28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT Key.
        /// </summary>
        public static string _0x29 {
            get {
                return ResourceManager.GetString("0x29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRINT Key.
        /// </summary>
        public static string _0x2A {
            get {
                return ResourceManager.GetString("0x2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXECUTE Key.
        /// </summary>
        public static string _0x2B {
            get {
                return ResourceManager.GetString("0x2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRINT SCREEN Key.
        /// </summary>
        public static string _0x2C {
            get {
                return ResourceManager.GetString("0x2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT Key.
        /// </summary>
        public static string _0x2D {
            get {
                return ResourceManager.GetString("0x2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE Key.
        /// </summary>
        public static string _0x2E {
            get {
                return ResourceManager.GetString("0x2E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HELP Key.
        /// </summary>
        public static string _0x2F {
            get {
                return ResourceManager.GetString("0x2F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num 0 Key.
        /// </summary>
        public static string _0x30 {
            get {
                return ResourceManager.GetString("0x30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num 1 Key.
        /// </summary>
        public static string _0x31 {
            get {
                return ResourceManager.GetString("0x31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num 2 Key.
        /// </summary>
        public static string _0x32 {
            get {
                return ResourceManager.GetString("0x32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num 3 Key.
        /// </summary>
        public static string _0x33 {
            get {
                return ResourceManager.GetString("0x33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num 4 Key.
        /// </summary>
        public static string _0x34 {
            get {
                return ResourceManager.GetString("0x34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num 5 Key.
        /// </summary>
        public static string _0x35 {
            get {
                return ResourceManager.GetString("0x35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num 6 Key.
        /// </summary>
        public static string _0x36 {
            get {
                return ResourceManager.GetString("0x36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num 7 Key.
        /// </summary>
        public static string _0x37 {
            get {
                return ResourceManager.GetString("0x37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num 8 Key.
        /// </summary>
        public static string _0x38 {
            get {
                return ResourceManager.GetString("0x38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num 9 Key.
        /// </summary>
        public static string _0x39 {
            get {
                return ResourceManager.GetString("0x39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A Key.
        /// </summary>
        public static string _0x41 {
            get {
                return ResourceManager.GetString("0x41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a B Key.
        /// </summary>
        public static string _0x42 {
            get {
                return ResourceManager.GetString("0x42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C Key.
        /// </summary>
        public static string _0x43 {
            get {
                return ResourceManager.GetString("0x43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a D Key.
        /// </summary>
        public static string _0x44 {
            get {
                return ResourceManager.GetString("0x44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E Key.
        /// </summary>
        public static string _0x45 {
            get {
                return ResourceManager.GetString("0x45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F Key.
        /// </summary>
        public static string _0x46 {
            get {
                return ResourceManager.GetString("0x46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a G Key.
        /// </summary>
        public static string _0x47 {
            get {
                return ResourceManager.GetString("0x47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a H Key.
        /// </summary>
        public static string _0x48 {
            get {
                return ResourceManager.GetString("0x48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I Key.
        /// </summary>
        public static string _0x49 {
            get {
                return ResourceManager.GetString("0x49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a J Key.
        /// </summary>
        public static string _0x4A {
            get {
                return ResourceManager.GetString("0x4A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a K Key.
        /// </summary>
        public static string _0x4B {
            get {
                return ResourceManager.GetString("0x4B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a L Key.
        /// </summary>
        public static string _0x4C {
            get {
                return ResourceManager.GetString("0x4C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M Key.
        /// </summary>
        public static string _0x4D {
            get {
                return ResourceManager.GetString("0x4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N Key.
        /// </summary>
        public static string _0x4E {
            get {
                return ResourceManager.GetString("0x4E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a O Key.
        /// </summary>
        public static string _0x4F {
            get {
                return ResourceManager.GetString("0x4F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P Key.
        /// </summary>
        public static string _0x50 {
            get {
                return ResourceManager.GetString("0x50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Q Key.
        /// </summary>
        public static string _0x51 {
            get {
                return ResourceManager.GetString("0x51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a R Key.
        /// </summary>
        public static string _0x52 {
            get {
                return ResourceManager.GetString("0x52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a S Key.
        /// </summary>
        public static string _0x53 {
            get {
                return ResourceManager.GetString("0x53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T Key.
        /// </summary>
        public static string _0x54 {
            get {
                return ResourceManager.GetString("0x54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a U Key.
        /// </summary>
        public static string _0x55 {
            get {
                return ResourceManager.GetString("0x55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a V Key.
        /// </summary>
        public static string _0x56 {
            get {
                return ResourceManager.GetString("0x56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a W Key.
        /// </summary>
        public static string _0x57 {
            get {
                return ResourceManager.GetString("0x57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a X Key.
        /// </summary>
        public static string _0x58 {
            get {
                return ResourceManager.GetString("0x58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Y Key.
        /// </summary>
        public static string _0x59 {
            get {
                return ResourceManager.GetString("0x59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Z Key.
        /// </summary>
        public static string _0x5A {
            get {
                return ResourceManager.GetString("0x5A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Windows Key.
        /// </summary>
        public static string _0x5B {
            get {
                return ResourceManager.GetString("0x5B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Windows Key.
        /// </summary>
        public static string _0x5C {
            get {
                return ResourceManager.GetString("0x5C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apps Key.
        /// </summary>
        public static string _0x5D {
            get {
                return ResourceManager.GetString("0x5D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sleep Key.
        /// </summary>
        public static string _0x5F {
            get {
                return ResourceManager.GetString("0x5F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NumPad 0.
        /// </summary>
        public static string _0x60 {
            get {
                return ResourceManager.GetString("0x60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NumPad 1.
        /// </summary>
        public static string _0x61 {
            get {
                return ResourceManager.GetString("0x61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NumPad 2.
        /// </summary>
        public static string _0x62 {
            get {
                return ResourceManager.GetString("0x62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NumPad 3.
        /// </summary>
        public static string _0x63 {
            get {
                return ResourceManager.GetString("0x63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NumPad 4.
        /// </summary>
        public static string _0x64 {
            get {
                return ResourceManager.GetString("0x64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NumPad 5.
        /// </summary>
        public static string _0x65 {
            get {
                return ResourceManager.GetString("0x65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NumPad 6.
        /// </summary>
        public static string _0x66 {
            get {
                return ResourceManager.GetString("0x66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NumPad 7.
        /// </summary>
        public static string _0x67 {
            get {
                return ResourceManager.GetString("0x67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NumPad 8.
        /// </summary>
        public static string _0x68 {
            get {
                return ResourceManager.GetString("0x68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NumPad 9.
        /// </summary>
        public static string _0x69 {
            get {
                return ResourceManager.GetString("0x69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiply Key.
        /// </summary>
        public static string _0x6A {
            get {
                return ResourceManager.GetString("0x6A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Key.
        /// </summary>
        public static string _0x6B {
            get {
                return ResourceManager.GetString("0x6B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Separator Key.
        /// </summary>
        public static string _0x6C {
            get {
                return ResourceManager.GetString("0x6C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtract Key.
        /// </summary>
        public static string _0x6D {
            get {
                return ResourceManager.GetString("0x6D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decimal Key.
        /// </summary>
        public static string _0x6E {
            get {
                return ResourceManager.GetString("0x6E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divide Key.
        /// </summary>
        public static string _0x6F {
            get {
                return ResourceManager.GetString("0x6F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F1 Key.
        /// </summary>
        public static string _0x70 {
            get {
                return ResourceManager.GetString("0x70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F2 Key.
        /// </summary>
        public static string _0x71 {
            get {
                return ResourceManager.GetString("0x71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F3 Key.
        /// </summary>
        public static string _0x72 {
            get {
                return ResourceManager.GetString("0x72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F4 Key.
        /// </summary>
        public static string _0x73 {
            get {
                return ResourceManager.GetString("0x73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F5 Key.
        /// </summary>
        public static string _0x74 {
            get {
                return ResourceManager.GetString("0x74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F6 Key.
        /// </summary>
        public static string _0x75 {
            get {
                return ResourceManager.GetString("0x75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F7 Key.
        /// </summary>
        public static string _0x76 {
            get {
                return ResourceManager.GetString("0x76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F8 Key.
        /// </summary>
        public static string _0x77 {
            get {
                return ResourceManager.GetString("0x77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F9 Key.
        /// </summary>
        public static string _0x78 {
            get {
                return ResourceManager.GetString("0x78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F10 Key.
        /// </summary>
        public static string _0x79 {
            get {
                return ResourceManager.GetString("0x79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F11 Key.
        /// </summary>
        public static string _0x7A {
            get {
                return ResourceManager.GetString("0x7A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F12 Key.
        /// </summary>
        public static string _0x7B {
            get {
                return ResourceManager.GetString("0x7B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F13 Key.
        /// </summary>
        public static string _0x7C {
            get {
                return ResourceManager.GetString("0x7C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F14 Key.
        /// </summary>
        public static string _0x7D {
            get {
                return ResourceManager.GetString("0x7D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F15 Key.
        /// </summary>
        public static string _0x7E {
            get {
                return ResourceManager.GetString("0x7E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F16 Key.
        /// </summary>
        public static string _0x7F {
            get {
                return ResourceManager.GetString("0x7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F17 Key.
        /// </summary>
        public static string _0x80 {
            get {
                return ResourceManager.GetString("0x80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F18 Key.
        /// </summary>
        public static string _0x81 {
            get {
                return ResourceManager.GetString("0x81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F19 Key.
        /// </summary>
        public static string _0x82 {
            get {
                return ResourceManager.GetString("0x82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F20 Key.
        /// </summary>
        public static string _0x83 {
            get {
                return ResourceManager.GetString("0x83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F21 Key.
        /// </summary>
        public static string _0x84 {
            get {
                return ResourceManager.GetString("0x84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F22 Key.
        /// </summary>
        public static string _0x85 {
            get {
                return ResourceManager.GetString("0x85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F23 Key.
        /// </summary>
        public static string _0x86 {
            get {
                return ResourceManager.GetString("0x86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F24 Key.
        /// </summary>
        public static string _0x87 {
            get {
                return ResourceManager.GetString("0x87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left SHIFT Key.
        /// </summary>
        public static string _0xA0 {
            get {
                return ResourceManager.GetString("0xA0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right SHIFT Key.
        /// </summary>
        public static string _0xA1 {
            get {
                return ResourceManager.GetString("0xA1", resourceCulture);
            }
        }
    }
}
